### ISSUE TITLE
Update to fix new solhint rules

### ISSUE THREAD

**Issue by edmundedgar** [RealityETH/subjectivocracy#101]
After doing a new checkout with a new `solhint` install it complains about new things, specifically `no-unused-import`, `custom-errors`, `one-contract-per-file`, `immutable-vars-naming` and `explicit-types`. Most of these are useful things we should just fix that should be quick. 

The one we might or might not want to do is 
`Use Custom Errors instead of require statements  custom-errors`
I guess we should definitely do it if it helps with code size limits. It'll be a bit of a laborious job, maybe one for AI, or one of us when we need some not-too-thinking-heavy work.

**Comment by josojo** [comment]
The package.json dicates whichc solhint version should be used. I would not install it globally and just use the one from the package.json.

Then we all have the same version and no trouble

**Comment by josojo** [comment]
Ed, can we close this?

**Comment by edmundedgar** [comment]
NBD but ideally I'd do the upgrade if and when we do #102 , it had a lot of useful stuff.
