### ISSUE TITLE
Replace revert strings with solidity errors

### ISSUE THREAD

**Issue by edmundedgar** [RealityETH/subjectivocracy#102]

**Comment by josojo** [comment]
reason why we wanna do this is: https://ethereum.stackexchange.com/questions/101782/requirecondition-message-vs-revert-with-a-custom-error-which-is-better-a

**Comment by edmundedgar** [comment]
Right. The gas cost probably doesn't make that much difference to us since we shouldn't need to deploy these contracts very often but it seems to be Best Practice nowadays. It makes the code longer but I like it better than the short require strings we've been using to satisfy the linter.

I wonder if this is the kind of job AI could do.
