### ISSUE TITLE
Combine deployFork and resolveFork into a single step

### ISSUE THREAD

**Issue by edmundedgar** [RealityETH/subjectivocracy#12]
Since we now do the auction before forking instead of after, it's probably better if resolveFork has already happened when we deploy the child contracts so that contracts on them can rely on the knowledge of what happened.

Work out how to combine deployFork and resolveFork into a single step, and also see if it's safe to do both deployFork transactions as a single transaction.

**Comment by josojo** [comment]
@edmundedgar This is no lnoger needed, right?
