### ISSUE TITLE
Rework update possiblity

### ISSUE THREAD

**Issue by josojo** [RealityETH/subjectivocracy#131]
Currently, there are two options to update the contracts. Either via the multisig or via a fork. 

I think we should limit it to one method, since two methods are just increasing the complexity and the attack surface

**Comment by edmundedgar** [comment]
Is the multisig option basically what's built in to the polygon contracts? Obviously changes to their code add the amount we need audited.

Also do we want to be able to do an uncontested upgrade that doesn't result in a fork? Early on it seems like we'll want to do upgrades like this, I think? ie we have an "owner" contract that makes a reality.eth game for "should we just upgrade this baby" and you only get a fork if that's escalated

**Comment by josojo** [comment]
>Is the multisig option basically what's built in to the polygon contracts? 
yes. But it's not complicated. It's basically the proxy construction that allows that

>Also do we want to be able to do an uncontested upgrade that doesn't result in a fork?
yes, you are right. Becuase of this, we need the mult-sig update anyways.

So the questions is whether we want to abandon the forking upgrading method.

**Comment by josojo** [comment]
Just linking our newest thoughts:
https://docs.google.com/document/d/1-Nysiv4cLJn9NtOBmNbRO79HN4KZaKm0lHRCRY_Sc2M/edit

**Comment by josojo** [comment]
#138 took care of it.
