### ISSUE TITLE
contract initialization could be done by anyone after a fork

### ISSUE THREAD

**Issue by josojo** [RealityETH/subjectivocracy#136]
The split of executeFork1 and executeFork2 caused that we are no longer executing these two operations atomically. This will allow someone else to initialize the new child contracts with the wrong parameters.

**Comment by edmundedgar** [comment]
Assuming we're good with the new upgrade plan we should be able to undo the splitting part, and also simplify the forking so it no longer needs to take all these parameters in the first place.
