### ISSUE TITLE
Make ForkArbitrator used by Adjudication Framework have an optional delay

### ISSUE THREAD

**Issue by edmundedgar** [RealityETH/subjectivocracy#146]
Related to #141, some questions may require a longer period than others to decide if there's fork. We can do this by having a minimum delay in the ForkingManager contract on L1, but also allowing a delay to be configured between requesting arbitration from the ForkArbitrator and calling the ForkingManager on L1.

**Comment by josojo** [comment]
I think there are three option to put the delay in:

1) ForkRequester L1
2) ForkArbitrator L2
3) AdjudicationFramework itself

Usually, a fork goes through all 3 levels. I think we end up with the least complexity, if the put in the delay at the earliest level, such that other levels don't have to deal with it. This means, I would put it even into the level #) adjudication framework.

Would you agree?

**Comment by edmundedgar** [comment]
Currently anyone can make an AdjucationFramework which ends up calling the L1 contracts that result in a fork (although at earlier points in the discussion we talked about restricting them), so the minimum time that the system requires to fork must be set in the L1 ForkingManager.

The logical place for the optional delay is the ForkArbitrator, since that's the thing that deals with the forks, not the AdjudicationFramework. However this may not apply if there are some different AdjucationFramework designs that don't use the ForkArbitrator.

**Comment by josojo** [comment]
>although at earlier points in the discussion we talked about restricting them

yes, this should be restricted, at least by social conensus.

>so the minimum time that the system requires to fork must be set in the L1 ForkingManager.

yes, this is how its implemented right now.

>The logical place for the optional delay is the ForkArbitrator, since that's the thing that deals with the forks, not the AdjudicationFramework.

and how do you imagine the forkArbitrator to decide on the delay? I think the delay should be individual for each arbitration-framework. And if the adjudicationframework anyhow knows about the delay, then it can also introduce it, right?
( I don't have a strong opinion)

Do you think there will be adjudicationFramworks that don't talk to the forkArbitrator? I can not come up with a logical example?

**Comment by edmundedgar** [comment]
Yeah, I guess the adjudication framework could implement it, or the forkarbitrator could hard-code it and the adjudication framework could take its settings when it choses the forkarbitrator, or the forkarbitrator could read it off the adjudication framework. Any of those seems fine to me, whatever seems cleanest to you
