### ISSUE TITLE
L1GlobalForkRequester: Don't allow returning tokens immediately

### ISSUE THREAD

**Issue by josojo** [RealityETH/subjectivocracy#170]
If we would allow tokens to be returned permissionlessly immediately, then a legitimte request that just needs to wait for another fork to resolve, could be aborted by returning the tokens.

I think a easy fix is to just wait for 2 weeks before one allows to returns the tokens.

**Comment by edmundedgar** [comment]
The code looks fine for doing what it says on the tin, I just need to wrap my head around the problem it solves and what's actually supposed to be happening if/when fork requests happen concurrently. I think my assumption was that you'd unwind them (but not yet unfreeze the underlying question) and resubmit. Maybe talk about this next time we do a call.
