### ISSUE TITLE
Suppport more tokens

### ISSUE THREAD

**Issue by josojo** [RealityETH/subjectivocracy#222]
bytes memory metadata = abi.encode(
            IERC20Metadata(token).name(),
            IERC20Metadata(token).symbol(),
            IERC20Metadata(token).decimals()
        );

Some tokens might not support those methods, one needs to call them using staticcall

**Comment by edmundedgar** [comment]
Is this an upstream polygon decision or did we do it?

**Comment by josojo** [comment]
I opened the Pr to make it clearer
