### ISSUE TITLE
wrong zkevm in ForkingManager?

### ISSUE THREAD

**Issue by edmundedgar** [RealityETH/subjectivocracy#75]
> IBasePolygonZkEVMGlobalExitRoot(newInstances.globalExitRoot.one),
> address(newInstances.zkEVM.two),
> address(newInstances.forkonomicToken.one),

looks like the middle one should be `address(newInstances.zkEVM.one)`

https://github.com/RealityETH/subjectivocracy/blob/main/development/contracts/ForkingManager.sol#L210

**Comment by josojo** [comment]
Good catch. yes this is right
