### ISSUE TITLE
Work out how to handle manage chain ID issuance

### ISSUE THREAD

**Issue by edmundedgar** [RealityETH/subjectivocracy#78]
Forkmanagers can exist up in parallel, so we can't just add a chain ID to the existing one. We instead need a single contract to issue chain IDs. 

(It may be useful to have this also act as a directory of l2 installs, so for example a contract on L2 can say, "the EVM says my chain ID is 1234, what's the ForkManager I should talk to when I need to fork this chain?")

Forkmanagers may be malicious, so we can't just allow ForkManagers to keep requesting all the chain IDs they like, in case they maliciously make lots of them to make them overlap with some other chain.

So we need either a payment (eg ETH burned), a delay or both, eg a tree of ForkingManagers has to make a payment to get a chain ID, and this increases the more parents it has in its tree, while dropping off as time passes. Alternatively, maybe the gas cost will be enough of a cost if we pick a high number so we have a wide range?

**Comment by josojo** [comment]
Another approach: Reusing chainIds
The global fork manager checks whether a deployed chainId's chain's native token is worth more than a certain threshold, and if not it reuses the chainId.
The algorithm for checking the price could be: 
- look at the price auctions after each split. If once the price is below a certain threshold, then all child chain's of this fork will be considered not to have valuable chains.

I am really not sure which option to pick from the three: Measure value, delay, or paymentt.

**Comment by edmundedgar** [comment]
I think reuse is bad even (especially?) if a branch ends up being worthless, because you may have signed a transaction to sell tokens when they were near-worthless and this can now be replayed on a fork that's worth more.

**Comment by josojo** [comment]
Ups, you are right. Sorry


Maybe then the payment option is the best. But I would love, if we are not burning eth, but rather burn forknomic tokens. Given that we can measure their forkonomic tokens prices in the auctions, we could calculate a price in each forknomic token and then charge these forknomic tokens worth x $.
But yeah, maybe its too complex and just burning eth is sufficient. Not sure

**Comment by edmundedgar** [comment]
I guess it may be possible to recycle these ETH for paying for sequenced batches or something, we don't necessarily have to burn them

**Comment by josojo** [comment]
Do you have more concrete ideas on how to recycle them? Maybe in each chain of parent-child a withdrawal of one per year is allowed? That means if one forks it quite often, one has to wait several years to withdraw?

**Comment by edmundedgar** [comment]
Just vaguely thinking something like, the ETH deposited to claim a chain ID is made available as a subsidy that can be claimed by whoever submits a proof to the zkevm contract of that chain.

**Comment by josojo** [comment]
I think we found a good enough solution. 

From the source code, the protection has the following caluclation:

// The burnGas function introduces a cost to use up chainIds.
        // There are uint64(2**63=9.223372e+18) chainIds minus the publicly used chainIds available.
        // Using all of the chainIds would cost 9.223372e+18 * gasBurnAmount = 9.223372e+24 gas = 6.1489147e+17 blocks = 237226647377 years
