### ISSUE TITLE
Let l2 contracts know how to talk to ForkingManager

### ISSUE THREAD

**Issue by edmundedgar** [RealityETH/subjectivocracy#79]
When we request a fork with a L2 contract but the forking is on L1, we need to somehow get a message to the ForkingManager. The address of ForkingManager will change across forks. Presumably there's a built-in address that doesn't change on L2 that allows us to message the bridge on L1, whose address will also change.

Options:

1) Make a method against the bridge to forward from L2, eg `requestFork()`
2) Same but generic, eg `sendMessageToForkManager()`
3) Have a global directory contract on L1 that knows mappings of chain ID to ForkManager (and via ForkManager bridge), have that do forwarding like in 1 or 2
4) Have a single global contract on L1 that can send a message after the fork from L1 to L2 to a Directory contract on L2 telling it that Chain ID 123 has ForkManager 0xabc, the L2 contract checks that it has chain ID 123 (by evm) and records the ForkManager, then do normal requests across the bridge to 0xabc

Relatedly in the other direction: Each L2 needs to be able to find out what side it's on (yes fork or no fork), and possibly what it forked over. Not sure if we can submit proofs of L1 data direct to an L2 contract, if we can then do (3) above and prove the state of that contract? Or with the (4) approach, we can just send the data across with an L1->L2 message.

**Comment by josojo** [comment]
>When we request a fork with a L2 contract 

Due to censoring reasons, the esclation game about forking is on L1, right? Hence, I think we don't need to bridge the forking message, everything happens on L1, right?

**Comment by edmundedgar** [comment]
Plan: Add a contract that with a global address that can get a message and send the message on to the bridge's forkmanager.
