### ISSUE TITLE
Check contract cloning etc works on zksync

### ISSUE THREAD

**Issue by edmundedgar** [RealityETH/subjectivocracy#8]
Contract deployments on zksync are a bit different. We have some code that wants to clone contracts, use libraries etc. Check if there are any incompatibilities.

**Comment by edmundedgar** [comment]
Possible we need to do something with `isWithdrawalFinalized` and `isETHWithdrawalFinalized`. They keep a mapping to see what they've completed. Hopefully this can only happen within a bridge contract, which can be forked, so we don't need to do anything. But we may need to either make the `isWithdrawalFinalized` mapping forkable, or add extra checks so that you don't try to withdraw stuff from before or after the fork.

**Comment by josojo** [comment]
@ed should we close this one, given that we don't wanna use zksync in the short term?
