### ISSUE TITLE
Straighten out interface usage around ForkableBridge

### ISSUE THREAD

**Issue by edmundedgar** [RealityETH/subjectivocracy#80]
`ForkableBridge` implements `ForkableStructure` so it has methods like `forkmanager()` but the `IForkableStructure` doesn't include all the variables that `ForkableStructure` exposes, and `IForkableBridge` doesn't know that it's supposed to inherit `IForkableStructure`

**Comment by edmundedgar** [comment]
Also elsewhere we say `forkingManager` now not `forkmanager` so maybe should rename?

**Comment by josojo** [comment]
I tried to keep even the interfaces small, e.g. if one function of the interface is not needed by any contract, then I did not put it in there.

which function should I put into the interface of IForkableStructure? Note that _createChildren is private. The forkmanager and parentContract are the only variables that don't need to be accessed by another contract via an interface, IMO.
