### ISSUE TITLE
PriorityQueue needs to be forkable

### ISSUE THREAD

**Issue by edmundedgar** [RealityETH/subjectivocracy#9]
When forking, we need to either preserve the priority queue, or make sure it's empty.

If we're going to preserve it, we need to modify
`ethereum/contracts/zksync/libraries/PriorityQueue.sol`
so that it can check if it has a parent, and if so pop the messages off the parent before it starts returning its own.

**Comment by josojo** [comment]
no longer relevant as we will not rely on zksync
