### ISSUE TITLE
Sort out reuse of reality.eth code

### ISSUE THREAD

**Issue by edmundedgar** [RealityETH/subjectivocracy#90]
For now we have local copies of reality.eth contracts we use in `lib/reality-eth` because we needed to make small changes like the solc version. See if we can pull from the npm package instead, this may require some tweaks on the reality.eth side.

**Comment by josojo** [comment]
I think we should push these changes in the reality-eth repo on a special branch. Once done, we can have lib/reality-eth as a proper git submodule and checkout the specific branch

**Comment by edmundedgar** [comment]
Published the latest contracts intended for use by Backstop as `@reality.eth/contracts@4.0.0-rc.0`. 
https://www.npmjs.com/package/@reality.eth/contracts/v/4.0.0-rc.0

Will try importing from there and making the other changes we need on inherited versions.
